name: whatsapp_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  event_bus: ^2.0.0
  cron: ^0.6.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  dart_openai: ^5.0.0

  google_fonts: ^6.1.0
  universal_io: ^2.2.2
  
  yaru: ^1.2.1
  yaru_widgets: ^3.6.0
  yaru_colors: ^0.1.7
  yaru_icons: ^2.4.0

  simple_icons: ^10.1.3
  window_manager: ^0.3.8
  inqvine_core_ui: ^2.0.2
  paginated_list: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/